# Resource names follow project-functionality-environment.
version = 0.1

[default.build.parameters]
cached = true
parallel = false

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "kinetic-erp-backend-dev"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "ProjectName=kinetic-erp Environment=dev"

[dev.deploy.parameters]
stack_name = "kinetic-erp-backend-dev"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "ProjectName=kinetic-erp Environment=dev"

[prod.deploy.parameters]
stack_name = "kinetic-erp-backend-prod"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "ProjectName=kinetic-erp Environment=prod"
