# Resource names follow project-functionality-environment.
version = 0.1

[default.build.parameters]
cached = true
parallel = false

[dev.build.parameters]
cached = true
parallel = false

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "kinetic-erp-backend-dev"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "ProjectName=kinetic-erp Environment=dev CognitoUserPoolId=ap-south-1_VR0j65Lrj CognitoClientId=1546223as2mv83ru74e00eubkt FrontendOrigin=https://kenetic-new-frontend.vercel.app"

[dev.deploy.parameters]
stack_name = "kinetic-erp-backend-dev"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "ProjectName=kinetic-erp Environment=dev CognitoUserPoolId=ap-south-1_VR0j65Lrj CognitoClientId=1546223as2mv83ru74e00eubkt FrontendOrigin=https://kenetic-new-frontend.vercel.app"

[prod.deploy.parameters]
stack_name = "kinetic-erp-backend-prod"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "ProjectName=kinetic-erp Environment=prod"
