"""Generate JSON contracts and TypeScript request types from backend schemas."""
import argparse
import json
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import contracts, model


def ts_type(spec):
    if spec.get('enum'):
        return ' | '.join(json.dumps(value) for value in spec['enum'])
    if spec['type'] == 'object':
        return '{ ' + '; '.join(name + ('' if name in spec.get('required', []) else '?') + ': ' + ts_type(member) for name, member in spec['properties'].items()) + ' }'
    return {'string': 'string', 'number': 'number', 'integer': 'number', 'boolean': 'boolean', 'array': 'string[]'}[spec['type']]


def artifacts():
    root = Path(__file__).resolve().parents[2]
    schemas = json.loads(json.dumps(contracts.export()))
    for schema in schemas.values():
        for spec in schema['properties'].values():
            if spec.get('entity'):
                spec['pattern'] = '^' + model.PREFIXES[spec['entity']] + '_[0-9a-f]{32}$'
    lines = ['// Generated by backend/scripts/export_contracts.py. Do not edit.', '']
    names = {}
    for resource, schema in schemas.items():
        name = ''.join(word.capitalize() for word in resource.split('-')) + 'CreateRequest'
        names[resource] = name
        lines.append('export type ' + name + ' = {')
        for key, spec in schema['properties'].items():
            lines.append('  ' + key + ('' if key in schema['required'] else '?') + ': ' + ts_type(spec) + ';')
        lines.extend(['};', ''])
    lines.append('export type CreateRequests = {')
    lines.extend('  ' + json.dumps(resource) + ': ' + name + ';' for resource, name in names.items())
    lines.extend(['};', '', 'export type ReversalRequest = { reason: string; reference: string; requestId: string; expectedVersion: number };', ''])
    return {root / 'backend/docs/API_CONTRACTS.json': json.dumps(schemas, indent=2, sort_keys=True) + '\n',
            root / 'frontend/src/lib/generated/contracts.ts': '\n'.join(lines)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in artifacts().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise SystemExit('Regenerate stale contracts: ' + str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8')
        print(path.name)
